name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          cargo install cargo-wasi
      - name: Build
        run: cargo wasi build --verbose
